### ISSUE TITLE
Update from the original source

### ISSUE THREAD

**Issue by 14113** [techvoxinc/puma-plugin-dogstatsd#1]
If I'm right, this is the original gem https://github.com/yob/puma-plugin-statsd

They have different dependency https://github.com/yob/puma-plugin-statsd/blob/master/puma-plugin-statsd.gemspec#L13

Is it possible to update our (https://github.com/techvoxinc/puma-plugin-dogstatsd) gem too? Otherwise, we can't update puma to v. 3

This could be interesting: https://github.com/yob/puma-plugin-statsd#datadog-integration maybe we can use the original gem, instead of the fork?

**Comment by stephenwiebe** [comment]
Updated.
